[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/__/auth/*"
  to = "https://parkswap-36bb2.firebaseapp.com/__/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/__/firebase/*"
  to = "https://parkswap-36bb2.firebaseapp.com/__/firebase/:splat"
  status = 200
  force = true

[build.environment]
SECRETS_SCAN_ENABLED = "false"